name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "stable"

    - name: Build
      working-directory: ./hw01
      run: |
          go mod tidy
          go build -v ./...

    - name: Test
      working-directory: ./hw01
      run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
